Feature #319: support multiple ldap realms
cyrusimap/cyrus-sasl pull request #621
Opened 2020-08-07 08:52 UTC by jdehaan

Feature #319, cleanup of the original patch from John Newbigin

**Changes**:

- be able to handle several LDAP realm configurations within one daemon setup

This avoids ugly workarounds in practical setups and allows to use saslauthd as a "proxy" for several **different** LDAP realms. NOTE that this differs from the multiple servers setup in the `ldap_servers` for redundancy/failover.

2021-05-05 22:48 UTC, quanah commented
Please update your commit(s) to be signed off on in accordance with our DCO. Thanks!

2023-06-27 22:03 UTC, hyc commented
> KNOWN ISSUE:

>There seems to be an issue with the certificate verification in multiple realm mode. The child process seems to remember the TLS CA CERT file to use and uses randomly (depending on which worker process was selected) a wrong one. Not sure where this is persisted and how to remove it yet. Can be worked around by providing a global ldap_tls_cacert_file setting with all CA in it.

If that's the case, you probably need to move all of the TLS settings in lak_connect() to after the ldap_initialize(), and just set them on the lak->ld. Since you're dealing with different settings for different realms, should avoid doing any global LDAP settings at all, and all of them should just be on the lak->ld handle instead.

2023-06-27 22:05 UTC, hyc requested changes
See comment https://github.com/cyrusimap/cyrus-sasl/pull/621#issuecomment-1610279518

2023-06-28 05:42 UTC, jdehaan commented
You're fully right 🤦🏻 ... This was not needed in out case because of the special corner case that we had the same root certificate... In the end all this looks like supporting multiple reals is a use case not at all foreseen by the initial design of the tool. It might be wiser to close this PR unmerged after all since there are many difficulties to overcome left over and there is (I discovered that a bit late) a cleaner possible - but not straight-forward - setup using a meta backend:

https://ltb-project.org/documentation/sasl_delegation.html#pass-through-authentication-on-several-ldap-directories-with-openldap-meta-backend

![image](https://github.com/cyrusimap/cyrus-sasl/assets/261428/fbc5f35e-78aa-467c-8f49-55d8369d457d)

Thanks for your time and thorough review!

2023-06-28 16:48 UTC, hyc commented
Yeah, closing this in favor of using back-meta makes sense.

2023-06-28 16:48 UTC, closed without merging